
local_search_task:
  description: >
    Conduct a thorough search about {topic} in given documents.
    Try to get as much relevant information about {topic} and any topics directly or indirectly
    related to it.
  expected_output: >
    A list with bullet points of the information arranged from most relevant to least relevant.
    Also give file names from which information was sourced.
  agent: local_research_analyst